# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: prompt_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='prompt_service.proto',
  package='prompt',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14prompt_service.proto\x12\x06prompt\"\x1f\n\rPromptRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"2\n\x0ePromptResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2O\n\rPromptService\x12>\n\rProcessPrompt\x12\x15.prompt.PromptRequest\x1a\x16.prompt.PromptResponseb\x06proto3'
)




_PROMPTREQUEST = _descriptor.Descriptor(
  name='PromptRequest',
  full_name='prompt.PromptRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='prompt', full_name='prompt.PromptRequest.prompt', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=63,
)


_PROMPTRESPONSE = _descriptor.Descriptor(
  name='PromptResponse',
  full_name='prompt.PromptResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='prompt.PromptResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='prompt.PromptResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=115,
)

DESCRIPTOR.message_types_by_name['PromptRequest'] = _PROMPTREQUEST
DESCRIPTOR.message_types_by_name['PromptResponse'] = _PROMPTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PromptRequest = _reflection.GeneratedProtocolMessageType('PromptRequest', (_message.Message,), {
  'DESCRIPTOR' : _PROMPTREQUEST,
  '__module__' : 'prompt_service_pb2'
  # @@protoc_insertion_point(class_scope:prompt.PromptRequest)
  })
_sym_db.RegisterMessage(PromptRequest)

PromptResponse = _reflection.GeneratedProtocolMessageType('PromptResponse', (_message.Message,), {
  'DESCRIPTOR' : _PROMPTRESPONSE,
  '__module__' : 'prompt_service_pb2'
  # @@protoc_insertion_point(class_scope:prompt.PromptResponse)
  })
_sym_db.RegisterMessage(PromptResponse)



_PROMPTSERVICE = _descriptor.ServiceDescriptor(
  name='PromptService',
  full_name='prompt.PromptService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=117,
  serialized_end=196,
  methods=[
  _descriptor.MethodDescriptor(
    name='ProcessPrompt',
    full_name='prompt.PromptService.ProcessPrompt',
    index=0,
    containing_service=None,
    input_type=_PROMPTREQUEST,
    output_type=_PROMPTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PROMPTSERVICE)

DESCRIPTOR.services_by_name['PromptService'] = _PROMPTSERVICE

# @@protoc_insertion_point(module_scope)
